# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0518024efd9f94ec9a1b8c21cbaa4a1"
name = "sale-notifi"
handle = "sale-notifi"
application_url = "https://maple-com-camp-potter.trycloudflare.com/auth/shopify"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "elgnut.myshopify.com"

[auth]
redirect_urls = [
  "https://maple-com-camp-potter.trycloudflare.com/auth/shopify/callback",
  "https://maple-com-camp-potter.trycloudflare.com/authSa/shopify/callback",
  "https://maple-com-camp-potter.trycloudflare.com/auth/shopify/embed/callback",
  "https://maple-com-camp-potter.trycloudflare.com/auth/shopify/embed/callback/updateScopes",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false
